/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Atchara {
  constructor(schemaJs: object, defsJs?: Array<object> | undefined | null)
  /**
   * Parse JSON from UTF-8 encoded bytes to schema-driven binary format.
   * Returns (is_error, json_encoded_data) tuple:
   */
  parse(input: Uint8Array): [boolean, Buffer]
  /**
   * Begin a streaming parse session for incremental large document parsing.
   * Returns a StreamingSession that accepts chunks of data.
   */
  createStreamingSession(): StreamingSession
  /**
   * Begin an iterating parse session for streaming array element access.
   * Only valid when the root schema is an array.
   * Returns (IteratingSession, RedbClient) — session for feeding data, redb for reading.
   */
  createIteratingSession(): [IteratingSession, RedbClient]
}

export declare class IteratingSession {
  /** Feed a chunk and return all element indices that became ready. */
  feed(chunk: Buffer): IteratingFeedResult
  /** Signal EOF and process any remaining data. */
  finish(): IteratingFeedResult
  /**
   * Abort iteration, dropping the driver. Idempotent.
   * RedbClient handles database cleanup independently.
   */
  abort(): void
  /** Get memory stats for profiling. */
  getMemoryStats(): NativeMemoryStats
}

/** Uses RefCell<Option<Database>> for explicit close() support while remaining GC-safe. */
export declare class RedbClient {
  /** Whether the session has been closed */
  get isClosed(): boolean
  /**
   * Close the session, releasing all resources.
   * Safe to call multiple times (idempotent).
   */
  close(): void
  /** Get value at key */
  get(key: string): Buffer | null
  /** Get all keys with prefix (for record key enumeration) */
  keysWithPrefix(prefix: string): Array<string>
}

/**
 * Streaming session for incremental large document parsing.
 * Thin N-API wrapper — delegates parse orchestration to `StreamingDriver`.
 */
export declare class StreamingSession {
  /**
   * Feed a chunk of data to the parser.
   * Returns (status, error_bytes) where:
   * - status = -1: error (error_bytes contains encoded error)
   * - status = 1: ok (needs more data or parsing complete)
   */
  feed(chunk: Buffer): [number, Buffer]
  /** Finish parsing and return the session for accessing parsed data. */
  finish(): [boolean, Buffer, RedbClient | undefined | null]
  /** Get memory stats for profiling. */
  getMemoryStats(): NativeMemoryStats
  /** Abort the session, cleaning up resources. */
  abort(): void
}

/** Sentinel value for absent optional fields in object offset tables */
export const ABSENT_FIELD_MARKER: number

export const ERROR_CODE_INVALID_SCHEMA: number

export const ERROR_CODE_INVALID_UTF8: number

export const ERROR_CODE_MISSING_REQUIRED: number

export const ERROR_CODE_UNEXPECTED_CHARACTER: number

export const ERROR_CODE_UNEXPECTED_EOF: number

export const ERROR_CODE_UNEXPECTED_FIELD: number

export const ERROR_CODE_UNION_NO_MATCH: number

export const ERROR_CODE_VALIDATION_ERROR: number

/**
 * FNV-1a 64-bit hash function for record key lookup.
 * Must match the encoding side exactly for binary search to work.
 */
export declare function fnv1A64(input: string): bigint

export interface IteratingFeedResult {
  /** -1 = error, 0 = complete, 1 = needs more data */
  status: number
  /** Element indices that are ready to read */
  readyIndices: Array<number>
  /** Encoded error bytes (only when status = -1) */
  errorBytes: Buffer
}

export interface NativeMemoryStats {
  inputBufferSize: number
  inputBufferCapacity: number
  parsePosition: number
  committedPosition: number
  compactionCount: number
  pendingWritesCount: number
  pendingWritesBytes: number
}

/** Flag indicating null value in nullable types */
export const NULL_FLAG: number

/** Flag indicating value is present in nullable types */
export const PRESENT_FLAG: number

/** Get version information */
export declare function version(): string
